### ISSUE TITLE
Option to View HTML Source

### ISSUE THREAD

**Issue by mobeeniqbal** [chigkim/AME#1]
I have just found this program and am liking it alot. The option to view the HTML output as it would be displayed in realtime is fantastic. Could you please add an option on the tabs to view the raw HTML source as well? There are certain online editors where I am required to paste the raw code when editing website pages etc. It may also be useful for example to be able to open a HTML file and edit it using markdown. Also, when adding multiple blank lines in markdown, they don't seem to be displaying on the HTML preview tab. I have not yet tried exporting to HTML to see if the blank lines show up there. Keep up the excellent work!

**Comment by chigkim** [comment]
Thanks for the suggestions.

1. You can save it as html and look at the html source.

2. I'm relying on a markdown library to translate md to html, and the library has no backward translation feature from html to md since html is so much richer than md.

3. For same reason, I don't have control over how newline in md gets rendered into html.

**Comment by chigkim** [comment]
Now there's an option to copy html source to the clipboard. control+shift+c
